name: ci

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        
      - name: SEMVER - Load
        id: read-properties
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Sources/Properties.proj
        
      - name: SEMVER - Determine.
        id: get-semantic-version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.read-properties.outputs.content }}
          regex: '<Version>(.*?)</Version>'  
        
      - name: NUGET - Source
        run: nuget sources Add -Name Artifactory -Source https://silvester.jfrog.io/artifactory/api/nuget/silvester-nuget/silvester-pathfinder/Silvester.Pathfinder.Official.Documents -username ${{ secrets.ARTIFACTORY_USERNAME }} -password ${{ secrets.ARTIFACTORY_PASSWORD }}
        
      - name: NUGET - Push
        if: ${{ steps.set-tag.outputs.tag != 'master'}}
        run: nuget push ../build/Silvester.Pathfinder.Official.Documents.${{ steps.get-semantic-version.outputs.group1 }}.nupkg -Source Artifactory
        
      - name: DOCKER - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: silvester.jfrog.io
    
      - name: DOCKER - Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: DOCKER - Setup BuildX
        uses: docker/setup-buildx-action@v1
        
      - name: DOCKER - Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true 
          build-args: |
            artifactoryUsername=${{ secrets.ARTIFACTORY_USERNAME }}
            artifactoryPassword=${{ secrets.ARTIFACTORY_PASSWORD }}
          tags: |
            silvester.jfrog.io/silvester-docker/pathfinder-official-api:${{ steps.get-semantic-version.outputs.group1 }}
            silvester.jfrog.io/silvester-docker/pathfinder-official-api:latest
